### PR TITLE
add Romanian data

### PR DESCRIPTION
**Pull request by altblue**

### CODE REVIEW

**Comment by tbrowder** [comment]
Thanks for the submission, @altblue. I'll try to look at this later today. In the meantime, if you can fix the test failure that would be great. But it may be my problem.

**Comment by altblue** [comment]
> Thanks for the submission, @altblue. I'll try to look at this later today. In the meantime, if you can fix the test failure that would be great. But it may be my problem.

Checked CI output, but have no idea what should I fix, as it seems to be croaking during dependencies installation.

**Comment by tbrowder** [comment]
Yes, it is my problem and I should be able to fix it. I have had a similar problem with other modules recently and did get eventually get them to work.

**Comment by tbrowder** [comment]
@altblue, I would appreciate any feedback on the instructions for adding a new language, especially via a new PR on its own branch.

**Comment by altblue** [comment]
I don't understand what you mean:

> I would appreciate any feedback on the instructions for adding a new language,

from this part I reckon you want comments on [docs/CONTRIBUTING](https://github.com/tbrowder/Date-Names/blob/master/docs/CONTRIBUTING.md)

> especially via a new PR on its own branch.

but this part baffles me, as I don't have any remarks to add, and, anyway, any such comments would be extraneous to commit.

So I have to ask to please explain what additional info you want me to submit? Thanks.

**Comment by tbrowder** [comment]
On Wed, Jan 13, 2021 at 11:34 altblue <notifications@github.com> wrote:

> I don't understand what you mean:
>
> I would appreciate any feedback on the instructions for adding a new
> language,
>
> from this part I reckon you want comments on docs/CONTRIBUTING
> <https://github.com/tbrowder/Date-Names/blob/master/docs/CONTRIBUTING.md>
>
That is correct.  I want to know if you had any problems with the
instructions in CONTRIBUTING for how to add a new language.  If you didn't,
that is fine and nothing is required.

**Review by tbrowder — APPROVED** [review]

**Comment by tbrowder** [comment]
Thanks @altblue!

**Comment by tbrowder** [comment]
u

**Pull request merged**
