### PR TITLE
Added Norwegian Nynorsk

### PR DESCRIPTION
**Pull request by zerodogg**
Data for Norwegian Nynorsk (Norway has two written languages, Nynorsk (nn) and Bokmål (nb)).

### CODE REVIEW

**Comment by tbrowder** [comment]
Thank you for the PR. I will try to incorporate it soon, but I first need to get the tests working again.

**Comment by tbrowder** [comment]
I've changed from Travis to Github workflow testing. I'll test on my local host...

**Comment by zerodogg** [comment]
Great, thanks for merging :) :+1:

**Comment by tbrowder** [comment]
On Tue, Oct 13, 2020 at 02:13 Eskild Hustvedt <notifications@github.com>
wrote:

> Great, thanks for merging :) 👍
>

You are most welcome, you made it very easy to do!

**Pull request merged**
